apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  type: NodePort
  ports:
    - name: rabbitmq-main   
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 30000   
    - name: rabbitmq-management  
      protocol: TCP
      port: 15672
      targetPort: 15672 
      nodePort: 31000   
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: rabbitmq
  replicas: 1  
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: "rabbitmq:3-management"
          ports:
            - containerPort: 5672
            - containerPort: 15672  
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: username
            - name: RABBITMQ_DEFAULT_PASS
              value: password
          volumeMounts:
            - name: rabbitmq-volume
              mountPath: /var/lib/rabbitmq
            - name: rabbitmq-config
              mountPath: /etc/rabbitmq
      volumes:
        - name: rabbitmq-volume
          emptyDir: {}
        - name: rabbitmq-config
          configMap:
            name: rabbitmq-config  

