services:
  mysql:
    image: mysql
    restart: always 
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=sample 
      - MYSQL_PASSWORD=password
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
      - mysqldb-data:/var/lib/mysql

  user:
    build: ./
    depends_on:
      - mysql
    environment:
      - dbURL=mysql+mysqlconnector://sample:password@mysql:3306/mydb
    ports:
      - "5001:5000"
    
volumes:
  mysqldb-data: