version: "3.9"


services:
  hotelSearch:
    container_name: hotelFinder
    build: ./
    ports:
      - 5003:3000
    environment:
      - mongoURL=mongodb://ak:password@mongo:27017/
      - serpapiKey=f3f6e4266e8a55e158eccff91716b1033839ff2368200bf47edd94ef78e8484b
    volumes:
      - ./:/usr/src/app

