openapi: 3
info:
  title: Hotel Search API
  description: API to fetch hotel search results from Google Hotel API and store in MongoDB
  version: 1.0.0
servers:
  - url: http://localhost:5003
paths:
  /hotels:
    post:
      summary: Fetch hotel search results
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                location:
                  type: string
                  description: Location to search for hotels
                check_in_date:
                  type: string
                  format: date
                  description: Check-in date
                check_out_date:
                  type: string
                  format: date
                  description: Check-out date
                guests:
                  type: integer
                  description: Number of guests
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    description: Fetched hotel search results
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
